name: Build Packages

on:
  push:
    branches:
      - stable

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Archive Package
        run: |
          zip -r "tgs_windows.zip" ./dist/tgs

      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: tgs_windows
          path: "./tgs_windows.zip"

  build_macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Archive Package
        run: |
          zip -r "tgs_macos.zip" ./dist/tgs

      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: tgs_macos
          path: "./tgs_macos.zip"

  build_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Archive Package
        run: |
          zip -r "tgs_linux.zip" ./dist/tgs

      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: tgs_linux
          path: "./tgs_linux.zip"
