name: Build Packages

on:
  push:
    branches:
      - main

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Install default dependencies
        run: pip install -r requirements.txt

      - name: Install api dependencies
        run: pip install -r requirements_api.txt

      - name: Build Package
        run: |
          pyinstaller src/main.py --name tgs --onefile --clean --noconsole

      - name: Archive Package
        run: |
          Compress-Archive -Path ./dist -DestinationPath "tgs_windows.zip"

      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: tgs_windows
          path: "./tgs_windows.zip"

  build_macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Install default dependencies
        run: pip install -r requirements.txt

      - name: Install api dependencies
        run: pip install -r requirements_api.txt

      - name: Build Package
        run: |
          pyinstaller src/main.py --name tgs --onefile --clean --noconsole

      - name: Archive Package
        run: |
          zip -r "tgs_macos.zip" ./dist

      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: tgs_macos
          path: "./tgs_macos.zip"

  build_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Install default dependencies
        run: pip install -r requirements.txt

      - name: Install api dependencies
        run: pip install -r requirements_api.txt

      - name: Build Package
        run: |
          pyinstaller src/main.py --name tgs --onefile --clean --noconsole

      - name: Archive Package
        run: |
          zip -r "tgs_linux.zip" ./dist

      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: tgs_linux
          path: "./tgs_linux.zip"
